### PR TITLE
[MS-710] Add UNCOOPERATIVE_CHILD exit option

### PR DESCRIPTION
**Pull request by meladRaouf**

### CODE REVIEW

**Review by luhmirin-s — APPROVED** [review]
Would it be an overkill to only show the option if child biometrics are being collected in the project?

**Comment by meladRaouf** [comment]
> Would it be an overkill to only show the option if child biometrics are being collected in the project?
@luhmirin-s I think this is a great idea.  
@jonsimprints, what are your thoughts? Should we display this exit option only when child bio is active?

**Comment by jonsimprints** [comment]
@meladRaouf how would we objectively define a child?

**Comment by meladRaouf** [comment]
> @meladRaouf how would we objectively define a child?

Good question,
If any SDK is enabled and the age limit is below, for example, 6 years, we can conclude that this SDK supports child bio.

**Pull request merged**
