### PR TITLE
[MS-742] Remove ProGuard rules from library modules and consolidate them in the app module

### PR DESCRIPTION
**Pull request by meladRaouf**
- Removed `proguard-rules.pro` files from all library modules.
- Consolidated ProGuard rules in the id module, as we have minimal custom rules per module.
- Simplifies project structure and ensures consistent ProGuard handling across all modules.

### CODE REVIEW

**Review by luhmirin-s — COMMENTED** [review]
I see all the removals, but not many are added back to the app module. Aren't the hilt, jni and webview rules required for something?

**Comment by meladRaouf** [comment]
> I see all the removals, but not many are added back to the app module. Aren't the hilt, jni and webview rules required for something?

@luhmirin-s

I found that the Hilt rules are automatically added to the app's ProGuard rules file.
 As for the other `com.simprints.**` rules, they are also included in the same app-wide file. 
About the WebView rules—where did you get them from?

**Comment by luhmirin-s** [comment]
> I found that the Hilt rules are automatically added to the app's ProGuard rules file. As for the other `com.simprints.**` rules, they are also included in the same app-wide file. About the WebView rules—where did you get them from?

In this file - fingerprint/infra/simafis-wrapper/consumer-rules.pro

**Comment by meladRaouf** [comment]
> > I found that the Hilt rules are automatically added to the app's ProGuard rules file. As for the other `com.simprints.**` rules, they are also included in the same app-wide file. About the WebView rules—where did you get them from?
> 
> In this file - fingerprint/infra/simafis-wrapper/consumer-rules.pro

@luhmirin-s it is a commented code

**Review by luhmirin-s — APPROVED** [review]

**Pull request merged**
